# Generated by Django 4.1 on 2022-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WSCDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wsc_name", models.CharField(max_length=250)),
                ("wsc_year", models.CharField(max_length=4)),
                ("wsc_location", models.CharField(max_length=200)),
                ("wsc_detail", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("wsc_active", models.BooleanField(default=False)),
            ],
        ),
    ]
